RECOVERY_PREBUILT_KERNEL_MODULES_PATH := $(KERNEL_PREBUILT_PATH)/modules
ifneq ($(wildcard $(RECOVERY_PREBUILT_KERNEL_MODULES_PATH)/lib/modules),)
RECOVERY_PREBUILT_KERNEL_MODULES_PATH := $(RECOVERY_PREBUILT_KERNEL_MODULES_PATH)/lib/modules
endif
RECOVERY_PREBUILT_KERNEL_MODULES_OUT := $(TARGET_RECOVERY_ROOT_OUT)/lib/modules
RECOVERY_PREBUILT_KERNEL_FILES := $(TARGET_PREBUILT_KERNEL) $(TARGET_PREBUILT_DTB) $(BOARD_PREBUILT_DTBOIMAGE)
RECOVERY_PREBUILT_KERNEL_FILES += $(shell find $(RECOVERY_PREBUILT_KERNEL_MODULES_PATH) -type f 2>/dev/null | sort)
RECOVERY_PREBUILT_KERNEL_DEPS := $(RECOVERY_PREBUILT_KERNEL_MODULES_PATH) $(RECOVERY_PREBUILT_KERNEL_FILES) $(RECOVERY_PREBUILT_KERNEL_MODULES_OUT)
RECOVERY_PREBUILT_KERNEL_STAMP := $(PRODUCT_OUT)/obj/PACKAGING/recovery_kernel_prebuilts_intermediates/hash.stamp

$(RECOVERY_PREBUILT_KERNEL_MODULES_OUT):
	$(hide) mkdir -p $@

$(RECOVERY_PREBUILT_KERNEL_STAMP): $(RECOVERY_PREBUILT_KERNEL_DEPS)
	$(hide) mkdir -p $(dir $@)
	$(hide) if [ -d "$(RECOVERY_PREBUILT_KERNEL_MODULES_PATH)" ]; then rm -rf $(RECOVERY_PREBUILT_KERNEL_MODULES_OUT) && mkdir -p $(RECOVERY_PREBUILT_KERNEL_MODULES_OUT) && cp -af $(RECOVERY_PREBUILT_KERNEL_MODULES_PATH)/. $(RECOVERY_PREBUILT_KERNEL_MODULES_OUT)/; fi
	$(hide) sha256sum $(RECOVERY_PREBUILT_KERNEL_FILES) > $@.tmp
	$(hide) if ! cmp -s $@.tmp $@; then mv $@.tmp $@; else rm $@.tmp; fi

$(recovery_ramdisk): $(RECOVERY_PREBUILT_KERNEL_STAMP)

$(INSTALLED_BOOTIMAGE_TARGET): $(MKBOOTIMG) $(INTERNAL_BOOTIMAGE_FILES) $(BOOTIMAGE_EXTRA_DEPS)
	$(call pretty,"Target boot image: $@")
	$(hide) $(MKBOOTIMG) --kernel $(call bootimage-to-kernel,$(1)) $(INTERNAL_BOOTIMAGE_ARGS) $(INTERNAL_MKBOOTIMG_VERSION_ARGS) $(BOARD_MKBOOTIMG_ARGS) --output $@
	$(hide) echo -n "SEANDROIDENFORCE" >> $@
	$(hide) $(call assert-max-image-size,$@,$(BOARD_BOOTIMAGE_PARTITION_SIZE),raw)
	@echo "Made boot image: $@"

$(INSTALLED_RECOVERYIMAGE_TARGET): $(MKBOOTIMG) $(recovery_ramdisk) $(recovery_kernel) $(RECOVERYIMAGE_EXTRA_DEPS) $(AVBTOOL) $(RECOVERY_PREBUILT_KERNEL_STAMP)
	@echo "----- Making recovery image ------"
	$(hide) $(MKBOOTIMG) $(INTERNAL_RECOVERYIMAGE_ARGS) $(INTERNAL_MKBOOTIMG_VERSION_ARGS) $(BOARD_MKBOOTIMG_ARGS) --output $@
	$(hide) echo -n "SEANDROIDENFORCE" >> $@
	$(hide) $(call assert-max-image-size,$@,$(BOARD_RECOVERYIMAGE_PARTITION_SIZE),raw)
	$(hide) $(AVBTOOL) add_hash_footer --image $@ --partition_size $(BOARD_RECOVERYIMAGE_PARTITION_SIZE) --partition_name recovery --algorithm $(BOARD_AVB_RECOVERY_ALGORITHM) --key $(BOARD_AVB_RECOVERY_KEY_PATH)
	@echo "Made recovery image: $@"
